-- V8: Event Lifecycle Dates
ALTER TABLE events
    ADD COLUMN IF NOT EXISTS registration_start TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS registration_end TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS event_start TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS event_end TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS submission_start TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS judging_start TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS judging_end TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS results_publish_at TIMESTAMP WITH TIME ZONE;
